vich_uploader:
    db_driver: orm

    mappings:
        rooms:
            uri_prefix: /images/rooms
            upload_destination: '%kernel.project_dir%/public/images/rooms'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
